/**
 * HotelFlow Design System - Color Palette
 * Generated by ui-ux-pro-max Skill (2026-07-24)
 * Style: Soft UI Evolution | Pattern: Real-Time Ops Dashboard
 * Primary: Navy (#1E3A8A) | Accent: Gold (#A16207) | Status: Green/Amber/Red
 */

export const LIGHT_MODE = {
  // Primary & Semantic (from Skill Design System)
  primary: '#1E3A8A',
  onPrimary: '#FFFFFF',
  secondary: '#3B82F6',
  accent: '#A16207',
  background: '#F8FAFC',
  foreground: '#1E40AF',
  muted: '#E9EEF5',
  border: '#BFDBFE',
  destructive: '#DC2626',
  ring: '#1E3A8A',

  // Surface & Text (Soft UI Evolution)
  surface: '#FFFFFF',
  surfaceSecondary: '#F8FAFC',
  text: '#1E293B',
  textSecondary: '#475569',
  textTertiary: '#94A3B8',

  // Status colors (semantic, dashboard-optimized)
  statusOpen: '#3B82F6',      // Blue - open tickets
  statusInProgress: '#F59E0B', // Amber - in progress
  statusClosed: '#10B981',    // Green - closed/resolved

  // Priority colors
  priorityLow: '#10B981',     // Green
  priorityMedium: '#F59E0B',  // Amber
  priorityHigh: '#EF4444',    // Red

  // Category colors (using skill palette)
  categoryComplaint: '#EF4444',    // Red (destructive)
  categoryInquiry: '#3B82F6',      // Blue (secondary)
  categoryBooking: '#10B981',      // Green (success)
  categoryOther: '#9CA3AF',        // Gray (muted)

  // Interactive
  hover: '#F1F5F9',
  focus: '#1E3A8A',
  focusRing: '#DBEAFE',

  // Sentiment
  sentimentPositive: '#10B981',
  sentimentNeutral: '#9CA3AF',
  sentimentNegative: '#EF4444',
};

export const DARK_MODE = {
  // Primary & Semantic (dark mode adjustments)
  primary: '#3B82F6',
  onPrimary: '#FFFFFF',
  secondary: '#60A5FA',
  accent: '#F59E0B',
  background: '#0F172A',
  foreground: '#93C5FD',
  muted: '#1E293B',
  border: '#1E3A8A',
  destructive: '#F87171',
  ring: '#3B82F6',

  // Surface & Text
  surface: '#1E293B',
  surfaceSecondary: '#334155',
  text: '#F1F5F9',
  textSecondary: '#CBD5E1',
  textTertiary: '#94A3B8',

  // Status colors (dark mode variants)
  statusOpen: '#60A5FA',      // Lighter blue
  statusInProgress: '#FCD34D', // Lighter amber
  statusClosed: '#34D399',    // Lighter green

  // Priority colors
  priorityLow: '#34D399',     // Green
  priorityMedium: '#FCD34D',  // Amber
  priorityHigh: '#F87171',    // Red

  // Category colors
  categoryComplaint: '#F87171',    // Red
  categoryInquiry: '#60A5FA',      // Blue
  categoryBooking: '#34D399',      // Green
  categoryOther: '#9CA3AF',        // Gray

  // Interactive
  hover: '#475569',
  focus: '#60A5FA',
  focusRing: '#1E3A8A',

  // Sentiment
  sentimentPositive: '#34D399',
  sentimentNeutral: '#9CA3AF',
  sentimentNegative: '#F87171',
};

export const getStatusColor = (status, isDark = false) => {
  const palette = isDark ? DARK_MODE : LIGHT_MODE;

  switch (status) {
    case 'open':
      return palette.statusOpen;
    case 'in_progress':
      return palette.statusInProgress;
    case 'closed':
      return palette.statusClosed;
    default:
      return palette.textTertiary;
  }
};

export const getPriorityColor = (priority, isDark = false) => {
  const palette = isDark ? DARK_MODE : LIGHT_MODE;

  switch (priority) {
    case 'low':
      return palette.priorityLow;
    case 'medium':
      return palette.priorityMedium;
    case 'high':
      return palette.priorityHigh;
    default:
      return palette.textSecondary;
  }
};

export const getCategoryColor = (category, isDark = false) => {
  const palette = isDark ? DARK_MODE : LIGHT_MODE;

  switch (category) {
    case 'complaint':
      return palette.categoryComplaint;
    case 'inquiry':
      return palette.categoryInquiry;
    case 'booking':
      return palette.categoryBooking;
    case 'other':
      return palette.categoryOther;
    default:
      return palette.textSecondary;
  }
};

export const getSentimentColor = (sentiment, isDark = false) => {
  const palette = isDark ? DARK_MODE : LIGHT_MODE;

  switch (sentiment) {
    case 'positive':
      return palette.sentimentPositive;
    case 'neutral':
      return palette.sentimentNeutral;
    case 'negative':
      return palette.sentimentNegative;
    default:
      return palette.sentimentNeutral;
  }
};

// German labels for UI display
export const CATEGORY_LABELS = {
  complaint: 'Beschwerde',
  inquiry: 'Anfrage',
  booking: 'Buchung',
  other: 'Sonstiges',
};

export const PRIORITY_LABELS = {
  high: 'Hoch',
  medium: 'Mittel',
  low: 'Niedrig',
};

export const STATUS_LABELS = {
  open: 'Offen',
  in_progress: 'In Bearbeitung',
  closed: 'Geschlossen',
};

export const SENTIMENT_LABELS = {
  positive: 'Zufrieden',
  neutral: 'Neutral',
  negative: 'Unzufrieden',
};
